In [1]:
import numpy as np

In [6]:
a =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
#accessing element (r_index, c_index)
a[1, :]

array([ 6,  7,  8,  9, 10])

In [14]:
a[:, 2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [16]:
#chaning the element
a[1, 2] = 11
print(a)

[[ 1  2  3  4  5]
 [ 6  7 11  9 10]]


In [20]:
#chaning all col values
a[:, 3] = 6
print(a)

[[ 1  2  3  6  5]
 [ 6  7 11  6 10]]


In [23]:
#can still be outside the s_bracket
a[:, 3] = [6, 5]
print(a)

[[ 1  2  3  6  5]
 [ 6  7 11  5 10]]


In [15]:
from bokeh.plotting import figure,show
from bokeh.io import output_notebook

In [16]:
plot = figure()

In [17]:
output_notebook()

In [18]:
x =[1,2,3]
y=[4,5,6]

In [32]:
plot.line(x, y)
plot.cross(x,y, size=15, color='green')

GlyphRenderer(id='1826', ...)

In [33]:
show(plot)

NameError: ignored